version: 2.1
executors:
  default:
    docker:
      - image: docker:17.09.0-ce-git
    environment:
      OWNER: guitarrapc
      IMAGE_NAME: docker-mysqldef
jobs:
  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          command: docker build --build-arg VCS_REF=$(git rev-parse --short HEAD) -t ${OWNER}/${IMAGE_NAME}:latest .
      - run:
          command: docker image save ${OWNER}/${IMAGE_NAME}:latest > ./docker-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./docker-image.tar
  push:
    executor: default
    steps:
      - setup_remote_docker:
          version: 17.09.0-ce
      - attach_workspace:
          at: .
      - run:
          command: docker load -i ./docker-image.tar
      - run:
          command: docker tag ${OWNER}/${IMAGE_NAME}:latest ${OWNER}/${IMAGE_NAME}:$CIRCLE_TAG
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push ${OWNER}/${IMAGE_NAME}
workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - push:
          context: dockerhub-login
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
